# 只支持 16:9!!! 
# 1920 * 1080
# 2560 * 1440
# 3840 * 2160

tech:
# 技术中心
  - [AUG突击步枪, -1]
work:
# 工作台
  - [5.45x39mm BS, -1]
medical:
# 制药台
  - [精密护甲维修包, -1]
armor:
# 防具台
  - [FS复合防弹衣, -1]
TESSERACT_PATH: .\dist\Tesseract-OCR\tesseract.exe
hotkey: f8
background_mode: false
debug_mode: false
