# 只支持 16:9!!! 
# 1920 * 1080
# 2560 * 1440
# 3840 * 2160

tech:
# 技术中心
  - [骨架狙击枪托, -1]
work:
# 工作台
  - [5.45x39mm BS, -1]
medical:
# 制药台
  - [精密头盔维修包, -1]
armor:
# 防具台
  - [精英防弹背心, -1]
auto_run_until_hour: 11
TESSERACT_PATH: Tesseract-OCR\tesseract.exe
hotkey: f8
debug_mode: false
auto_replenish:
  enabled: true
  threshold: 3
  quantity: 2
